require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Translator' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', :modular_headers => false
  
  target 'TranslatorTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'Translator-tvOS' do
  # Pods for Translator-tvOS
  
  target 'Translator-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
