default_platform :ios

ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "ekbm-uqpd-extc-atxt"

platform :ios do
    lane :build do
        match(type: 'appstore', readonly: true)
        gym(scheme: 'SaMott')
    end

    lane :deploy do
        build
        pilot(skip_waiting_for_build_processing: true, team_id: "117699359", username: "koshechkin-vlad@yandex.ru")
    end
end
