default_platform :ios

#https://docs.fastlane.tools/best-practices/continuous-integration/#application-specific-passwords
ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "app specific пароль для загрузки приложения в appstoreconnect"

ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

platform :ios do
    lane :build do
        match(type: 'appstore', readonly: true)
        gym(scheme: 'Translator')
    end

    lane :deploy do
        build
        pilot(skip_waiting_for_build_processing: true, team_id: "117699359", username: "koshechkin-vlad@yandex.ru")
    end
end
