default_platform :ios

#https://docs.fastlane.tools/best-practices/continuous-integration/#application-specific-passwords
ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "app specific пароль для загрузки приложения в appstoreconnect"

ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

platform :ios do
    lane :prod do
      produce(
        username: 'koshechkin-vlad@yandex.ru',
        app_identifier: 'ru.use-case.translate',
        app_name: 'SaMott',
        language: 'ru'
      )
    end

    lane :reg_dev do
        register_devices(
          devices: {
            "Имя устройства (например Nikita 6s)" => "UDID устройства"
          }
        )
    end
    lane :build do
        match(type: 'appstore', readonly: true)
        gym(scheme: 'SaMott')
    end

    lane :deploy do
        build
        pilot(skip_waiting_for_build_processing: true, team_id: "117699359", username: "koshechkin-vlad@yandex.ru")
    end
end
